@echo off
cls

set DRIVE_LETTER=%1:
set COMPILER_PATH=%DRIVE_LETTER%/TDM-GCC-64
set GAME_PATH=%DRIVE_LETTER%/Endeavor
set GAME_ENGINE_PATH=%DRIVE_LETTER%/Game_Engine

set PATH=%COMPILER_PATH%/bin;%COMPILER_PATH%/wxWidgets-3.1.0/lib;c:/windows

mingw32-make GAME_PATH=%GAME_PATH% COMPILER_PATH=%COMPILER_PATH% GAME_ENGINE_PATH=%GAME_ENGINE_PATH%
